// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NestledNooks.Data;

#nullable disable

namespace NestledNooks.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615120000_AddGuestEmailTemplates")]
    partial class AddGuestEmailTemplates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
