// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NestledNooks.Data;

#nullable disable

namespace NestledNooks.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614143000_AddStripeBookingPayments")]
    partial class AddStripeBookingPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
