// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NestledNooks.Data;

#nullable disable

namespace NestledNooks.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260604150000_FixSiteThemeSingletonId")]
public partial class FixSiteThemeSingletonId
{
}
